// frontend/src/pages/offer/OfferList.tsx
import React from 'react';
import { Table, Card, Tag } from 'antd';

const OfferList: React.FC = () => {
  const columns = [
    { title: '候选人', dataIndex: 'candidate', key: 'candidate' },
    { title: '应聘职位', dataIndex: 'position', key: 'position' },
    { title: 'Offer状态', dataIndex: 'status', key: 'status',
      render: (status: string) => <Tag color="green">{status}</Tag>
    },
  ];

  return (
    <div className="page-container">
      <div className="page-header">
        <h1 className="page-title">Offer管理</h1>
      </div>
      <Card>
        <Table columns={columns} dataSource={[]} rowKey="id" locale={{ emptyText: '暂无数据' }} />
      </Card>
    </div>
  );
};

export default OfferList;

// frontend/src/pages/offer/OfferList.vue
<template>
  <div class="page-container">
    <div class="page-header">
      <h1 class="page-title">Offer管理</h1>
    </div>
    <a-card>
      <a-table :columns="columns" :dataSource="dataSource" rowKey="id" :locale="{ emptyText: '暂无数据' }" />
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const dataSource = ref([])

const columns = [
  { title: '候选人', dataIndex: 'candidate', key: 'candidate' },
  { title: '应聘职位', dataIndex: 'position', key: 'position' },
  { title: 'Offer状态', dataIndex: 'status', key: 'status' }
]
</script>

<style scoped>
.page-container { padding: 24px; }
.page-header { margin-bottom: 24px; }
.page-title { font-size: 24px; font-weight: 600; margin: 0; }
</style>
