// frontend/src/pages/notification/NotificationList.tsx
import React from 'react';
import { Table, Card, Tag } from 'antd';

const NotificationList: React.FC = () => {
  const columns = [
    { title: '标题', dataIndex: 'title', key: 'title' },
    { title: '类型', dataIndex: 'type', key: 'type',
      render: (type: string) => <Tag color="blue">{type}</Tag>
    },
    { title: '时间', dataIndex: 'time', key: 'time' },
    { title: '状态', dataIndex: 'status', key: 'status',
      render: (status: string) => (
        <Tag color={status === '未读' ? 'red' : 'green'}>{status}</Tag>
      )
    },
  ];

  return (
    <div className="page-container">
      <div className="page-header">
        <h1 className="page-title">消息通知</h1>
      </div>
      <Card>
        <Table columns={columns} dataSource={[]} rowKey="id" locale={{ emptyText: '暂无数据' }} />
      </Card>
    </div>
  );
};

export default NotificationList;

// web/app/src/pages/notification/NotificationList.vue
<template>
  <div class="page-container">
    <div class="page-header">
      <h1 class="page-title">消息通知</h1>
    </div>
    <n-card :bordered="false" class="rounded-xl">
      <n-data-table :columns="columns" :data="dataSource" :row-key="(row: any) => row.id" />
    </n-card>
  </div>
</template>

<script setup lang="ts">
import { ref, h } from 'vue'
import { NTag } from 'naive-ui'

interface DataItem {
  id: string
  title: string
  type: string
  time: string
  status: string
}

const dataSource = ref<DataItem[]>([])

const columns = [
  { title: '标题', key: 'title', render: (row: DataItem) => row.title },
  { title: '类型', key: 'type', render: (row: DataItem) => row.type },
  { title: '时间', key: 'time', render: (row: DataItem) => row.time },
  { title: '状态', key: 'status', render: (row: DataItem) => h(NTag, { type: 'info' }, { default: () => row.status }) },
]
</script>

<style scoped>
.page-header { margin-bottom: var(--space-6); }
.page-title { font-size: var(--fs-24); font-weight: 600; margin: 0; }
</style>
